#!/bin/bash

# Also support `sh setup.sh` on systems where /bin/sh is dash.
if [ -z "${BASH_VERSION:-}" ]; then
	exec bash "$0" "$@"
fi

set -eo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
username="$(id -un)"
case "$(uname -s)/$(uname -m)" in
Linux/x86_64) system="x86_64-linux" ;;
Linux/aarch64 | Linux/arm64) system="aarch64-linux" ;;
Darwin/arm64) system="aarch64-darwin" ;;
Darwin/x86_64) system="x86_64-darwin" ;;
*)
	echo "Unsupported platform: $(uname -s)/$(uname -m)" >&2
	exit 1
	;;
esac

# install nix if not already
if ! command -v nix >/dev/null 2>&1; then
	echo "nix not found, installing nix"
	curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh
fi

# make a fresh Nix installation available in this shell
if ! command -v nix >/dev/null 2>&1; then
	if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
		. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
	elif [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
		. "$HOME/.nix-profile/etc/profile.d/nix.sh"
	fi
fi

if ! command -v nix >/dev/null 2>&1; then
	echo "nix is not available; restart your shell and rerun setup.sh" >&2
	exit 1
fi

# enable nix commands and flakes if not already configured
mkdir -p "$HOME/.config/nix"
if ! grep -qxF 'experimental-features = nix-command flakes' "$HOME/.config/nix/nix.conf" 2>/dev/null; then
	printf '\n%s\n' 'experimental-features = nix-command flakes' >>"$HOME/.config/nix/nix.conf"
fi

# Quote machine-specific values as Nix strings, including literal ${...}.
nix_string() {
	local value="$1"
	value="${value//\\/\\\\}"
	value="${value//\"/\\\"}"
	value="${value//\$\{/\\\$\{}"
	printf '"%s"' "$value"
}

# Keep machine-specific identity outside the repo. This local flake imports the
# repo configuration and is automatically found by plain `home-manager switch`.
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
hm_config="$config_dir/home-manager"
mkdir -p "$config_dir"
generated_dir="$(mktemp -d "$config_dir/.home-manager.XXXXXX")"
trap 'rm -rf "$generated_dir"' EXIT
cat >"$generated_dir/flake.nix" <<EOF
# Generated by dotfiles/setup.sh; shared configuration lives in the repo.
{
  inputs.dotfiles = {
    type = "path";
    path = $(nix_string "$repo_dir/home-manager");
  };
  outputs = { dotfiles, ... }: {
    homeConfigurations.$(nix_string "$username") = dotfiles.lib.mkHome {
      system = $(nix_string "$system");
      username = $(nix_string "$username");
      homeDirectory = $(nix_string "$HOME");
      dotfilesDirectory = $(nix_string "$repo_dir");
    };
  };
}
EOF

if [ -L "$hm_config" ] || ! cmp -s "$generated_dir/flake.nix" "$hm_config/flake.nix"; then
	if [ -e "$hm_config" ] || [ -L "$hm_config" ]; then
		backup_dir="$(mktemp -d "$hm_config.backup.XXXXXX")"
		mv "$hm_config" "$backup_dir/home-manager"
		echo "Existing Home Manager config backed up to $backup_dir/home-manager"
	fi
	mkdir -p "$hm_config"
	mv "$generated_dir/flake.nix" "$hm_config/flake.nix"
fi

# Refresh the local repo input on reruns (path inputs are otherwise locked).
nix flake update dotfiles --flake "$hm_config"

# Bootstrap Home Manager; programs.home-manager.enable installs the command.
if command -v home-manager >/dev/null 2>&1; then
	home-manager switch --flake "$hm_config#$username" -b backup
else
	nix run github:nix-community/home-manager -- switch --flake "$hm_config#$username" -b backup
fi
