command_timeout = 500

format = """
$nix_shell\
$python\
$conda\
$directory\
$fill\
$cmd_duration\
$git_branch\
$git_status\
\n$character
"""

[git_branch]
symbol = ""
format = '[ $branch $symbol ]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:color_bg1"
format = '[ $duration ]($style)'

[fill]
symbol = " "

[directory]
truncation_length = -1
truncation_symbol = "…/"

[nix_shell]
format = "[ $symbol $name ]($style)"
symbol = "󱄅"

[python]
format = "[ $virtualenv ]($style)"

[conda]
format = "[ $symbol$environment ]($style)"
