command_timeout = 500

format = """
$directory\
$fill\
$cmd_duration\
$git_branch\
$git_status\
\n$character
"""

[git_branch]
symbol = ""
format = '[ $branch $symbol ]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:color_bg1"
format = '[ $duration ]($style)'

[fill]
symbol = " "

[directory]
truncation_symbol = "…/"
